"""Regenerate tests/fixtures/schema_snapshot.sql from a real page set.

The snapshot holds only the schema (CREATE TABLE/INDEX/TRIGGER statements) —
no Tobii content — so it is committed and lets the unit tests run without the
proprietary fixture file.

Usage:  python scripts/dump_schema_snapshot.py [path-to-real.sps]
        (default: tests/fixtures/example.sps)
"""

import pathlib
import sqlite3
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEST = ROOT / "tests" / "fixtures" / "schema_snapshot.sql"


def main() -> int:
    source = pathlib.Path(
        sys.argv[1] if len(sys.argv) > 1 else ROOT / "tests" / "fixtures" / "example.sps"
    )
    if not source.exists():
        print(f"Source page set not found: {source}", file=sys.stderr)
        print("Run scripts/fetch_fixture.py first, or pass a path.", file=sys.stderr)
        return 1

    conn = sqlite3.connect(f"file:{source}?mode=ro", uri=True)
    try:
        version = conn.execute(
            "SELECT SchemaVersion FROM PageSetProperties LIMIT 1"
        ).fetchone()[0]
        statements = [
            row[0]
            for row in conn.execute(
                "SELECT sql FROM sqlite_master "
                "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' "
                "ORDER BY type DESC, name"  # tables first, then indexes
            )
        ]
    finally:
        conn.close()

    DEST.parent.mkdir(parents=True, exist_ok=True)
    with open(DEST, "w", encoding="utf-8") as handle:
        handle.write(
            f"-- TD Snap page-set schema, SchemaVersion {version}.\n"
            "-- Generated by scripts/dump_schema_snapshot.py; do not hand-edit.\n\n"
        )
        for statement in statements:
            handle.write(statement.rstrip().rstrip(";") + ";\n\n")
    print(f"Wrote {DEST} ({len(statements)} statements, SchemaVersion {version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
