-- TD Snap page-set schema, SchemaVersion 4.13.
-- Generated by scripts/dump_schema_snapshot.py; do not hand-edit.

CREATE TABLE "Button"(
"Id" integer primary key autoincrement not null ,
"Label" varchar ,
"LabelOwnership" integer ,
"Message" varchar ,
"ImageOwnership" integer ,
"BorderColor" integer ,
"BorderThickness" float ,
"FontFamily" varchar ,
"FontSize" float ,
"FontStyle" integer ,
"SmartSymLayout" integer ,
"CommandFlags" integer ,
"ContentType" integer ,
"SerializedContentTypeHandler" varchar ,
"ContentTag" varchar ,
"UseMessageRecording" integer ,
"UniqueId" varchar(36) ,
"ActiveContentType" integer ,
"LibrarySymbolId" integer ,
"PageSetImageId" integer ,
"MessageRecordingId" integer ,
"ElementReferenceId" integer ,
"SerializedMessageSoundMetadata" varchar , SymbolColorDataId integer DEFAULT(0), LinkIndicatorStyle integer);

CREATE TABLE ButtonPageLink( Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ButtonId INTEGER NOT NULL, PageUniqueId varchar(36) NOT NULL, FOREIGN KEY(ButtonId) REFERENCES Button(Id) ON DELETE CASCADE);

CREATE TABLE "ButtonUsage"(
"Id" integer primary key autoincrement not null ,
"Timestamp" bigint ,
"ButtonUniqueId" varchar(36) ,
"Modeling" integer ,
"AccessMethod" integer ,
"BlockId" integer );

CREATE TABLE "ButtonUsageBlock"(
"Id" integer primary key autoincrement not null ,
"UniqueId" varchar(36) ,
"StartTime" bigint ,
"Timestamp" bigint ,
"SyncHash" integer );

CREATE TABLE "CommandSequence"(
"Id" integer primary key autoincrement not null ,
"SerializedCommands" varchar ,
"ButtonId" integer );

CREATE TABLE "ElementPlacement"(
"Id" integer primary key autoincrement not null ,
"GridPosition" varchar ,
"GridSpan" varchar not null ,
"Visible" integer ,
"ElementReferenceId" integer ,
"PageLayoutId" integer );

CREATE TABLE "ElementReference"(
"Id" integer primary key autoincrement not null ,
"ElementType" integer ,
"Language" varchar ,
"AudioCue" varchar ,
"UseAudioCueRecording" integer ,
"ForegroundColor" integer ,
"BackgroundColor" integer ,
"AudioCueRecordingId" integer ,
"SerializedAudioCueSoundMetadata" varchar ,
"PageId" integer , SerializedAccessSettingOverrides varchar);

CREATE TABLE "MessageWindowElement"(
"Id" integer primary key autoincrement not null ,
"UseSymbols" integer ,
"ElementReferenceId" integer );

CREATE TABLE "Page"(
"Id" integer primary key autoincrement not null ,
"UniqueId" varchar(36) ,
"Title" varchar ,
"PageType" integer ,
"Language" varchar ,
"BackgroundColor" integer ,
"ContentTag" varchar ,
"Timestamp" bigint ,
"SyncHash" integer ,
"SerializedMetadata" varchar ,
"LibrarySymbolId" integer ,
"PageSetImageId" integer ,
"GridDimension" varchar ,
"MessageBarVisible" integer ,
"SceneVisible" integer ,
"GridVisible" integer , SerializedSymbolPersonColors varchar, SymbolColorDataId integer DEFAULT(0), VocabPlannerForcedVisible integer DEFAULT(0));

CREATE TABLE PageExtra ( Id INTEGER PRIMARY KEY, AccessedAt BIGINT, FOREIGN KEY(Id) REFERENCES Page(Id) ON DELETE CASCADE);

CREATE TABLE "PageLayout"(
"Id" integer primary key autoincrement not null ,
"PageLayoutSetting" varchar ,
"PageId" integer );

CREATE TABLE "PageSetData"(
"Id" integer primary key autoincrement not null ,
"Identifier" varchar ,
"Data" blob ,
"RefCount" integer );

CREATE TABLE "PageSetProperties"(
"Id" integer primary key autoincrement not null ,
"ContentIdentifier" varchar ,
"ContentVersion" varchar ,
"SchemaVersion" varchar ,
"UniqueId" varchar(36) ,
"Language" varchar ,
"Timestamp" bigint ,
"SyncHash" integer ,
"DefaultHomePageUniqueId" varchar(36) ,
"SerializedHomePageUniqueIdOverrides" blob ,
"DefaultKeyboardPageUniqueId" varchar(36) ,
"SerializedKeyboardPageUniqueIdOverrides" blob ,
"ToolBarUniqueId" varchar(36) ,
"DashboardUniqueId" varchar(36) ,
"MessageBarUniqueId" varchar(36) ,
"MessageBarVisible" integer ,
"ToolbarLocation" integer ,
"GridVisible" integer ,
"SceneVisible" integer ,
"FriendlyName" varchar ,
"Description" varchar ,
"IconImageId" integer ,
"SerializedPreferredGridDimensions" varchar ,
"GridDimension" varchar ,
"SmartSymLayout" integer ,
"FontFamily" varchar ,
"FontSize" float ,
"FontStyle" integer ,
"PageBackgroundColor" integer ,
"MessageBarBackgroundColor" integer ,
"MessageWindowBackgroundColor" integer ,
"MessageWindowHighlightColor" integer ,
"ToolBarBackgroundColor" integer ,
"MessageWindowTextColor" integer ,
"MessageWindowFontSize" float ,
"GridMarginFactor" float ,
"LinkIndicatorStyle" integer ,
"SerializedOffscreenButton1Commands" varchar ,
"SerializedOffscreenButton2Commands" varchar ,
"ToolBarGridDimension" varchar ,
"PreferNavigationButtons" integer ,
"MessageWindowFontFamily" varchar ,
"SerializedPagePageSetScanGroup" varchar ,
"SerializedToolbarPageSetScanGroup" varchar ,
"SerializedMessageBarPageSetScanGroup" varchar , SerializedSymbolPersonColors varchar, VocabPlannerEnabled integer DEFAULT(0), VocabPlannerCurrentListUniqueId varchar(36) DEFAULT('00000000-0000-0000-0000-000000000000'), AutomorphingModel integer DEFAULT(0), CapabilityFlags integer DEFAULT(255), SerializedConfigurationInfo varchar DEFAULT(''), ButtonSearchAllowDuplicateMatches integer DEFAULT(1), ButtonSearchShowHiddenPaths integer DEFAULT(0), ButtonSearchPathIsAccessible integer DEFAULT(1), SerializedLanguageSettingsCollection varchar, SerializedScrollButtonStyle varchar DEFAULT('{"UseDefault":"true","BackgroundColor":"16777215","BorderColor":"-7960954","ArrowColor":"-7960954","BorderWidth":"2.0"}'), LinkIndicatorCornerTabColor integer DEFAULT(1258291200), SerializedPageSetDefaults varchar DEFAULT('{"ButtonSearchAllowDuplicateMatches":"True","ButtonSearchShowHiddenPaths":"False","ButtonSearchPathIsAccessible":"True"}'));

CREATE TABLE "ScanGroup"(
"Id" integer primary key autoincrement not null ,
"Name" varchar ,
"ScanOrder" integer ,
"StayInside" integer ,
"Color" integer ,
"AudioCue" varchar ,
"UseAudioCueRecording" integer ,
"SerializedGridPositions" varchar ,
"AudioCueRecordingId" integer ,
"SerializedAudioCueSoundMetadata" varchar ,
"PageLayoutId" integer );

CREATE TABLE SymbolColorData(
Id integer primary key autoincrement not null,
Identifier varchar,
SerializedFromColors varchar,
SerializedToColors varchar );

CREATE TABLE "SyncData"(
"UniqueId" varchar(36) primary key not null ,
"Type" integer ,
"Timestamp" bigint ,
"SyncHash" integer ,
"Deleted" integer ,
"Description" varchar );

CREATE TABLE "Synchronization"(
"Id" integer primary key autoincrement not null ,
"SyncServerIdentifier" varchar ,
"PageSetTimestamp" bigint ,
"PageSetSyncHash" integer );

CREATE TABLE "VocabList"(
"Id" integer primary key autoincrement not null ,
"UniqueId" varchar(36) not null ,
"Name" varchar ,
"Timestamp" bigint ,
"SyncHash" integer );

CREATE TABLE VocabListEntry(
Id integer primary key autoincrement not null,
Text varchar,
VocabListId integer);

CREATE TABLE "Whiteboard"(
"Id" integer primary key autoincrement not null ,
"UniqueId" varchar(36) not null ,
"ThumbnailImageId" integer ,
"Timestamp" bigint ,
"SyncHash" integer );

CREATE TABLE "WhiteboardDoodlePath"(
"Id" integer primary key autoincrement not null ,
"ScaleX" float ,
"ScaleY" float ,
"PositionX" float ,
"PositionY" float ,
"Rotation" float ,
"SerializedPath" varchar ,
"SerializedPaint" varchar ,
"WhiteboardId" integer );

CREATE TABLE "WhiteboardImage"(
"Id" integer primary key autoincrement not null ,
"UniqueId" varchar(36) not null ,
"ScaleX" float ,
"ScaleY" float ,
"PositionX" float ,
"PositionY" float ,
"Rotation" float ,
"PageSetImageId" integer ,
"WhiteboardId" integer );

CREATE UNIQUE INDEX "ButtonUsageBlock_UniqueId" on "ButtonUsageBlock"("UniqueId");

CREATE INDEX "ButtonUsage_BlockId" on "ButtonUsage"("BlockId");

CREATE INDEX "ButtonUsage_ButtonUniqueId" on "ButtonUsage"("ButtonUniqueId");

CREATE INDEX "Button_ElementReferenceId" on "Button"("ElementReferenceId");

CREATE INDEX "Button_MessageRecordingId" on "Button"("MessageRecordingId");

CREATE INDEX "Button_PageSetImageId" on "Button"("PageSetImageId");

CREATE INDEX "CommandSequence_ButtonId" on "CommandSequence"("ButtonId");

CREATE INDEX "ElementPlacement_PageLayoutId" on "ElementPlacement"("PageLayoutId");

CREATE INDEX "ElementReference_AudioCueRecordingId" on "ElementReference"("AudioCueRecordingId");

CREATE INDEX "ElementReference_PageId" on "ElementReference"("PageId");

CREATE INDEX "MessageWindowElement_ElementReferenceId" on "MessageWindowElement"("ElementReferenceId");

CREATE INDEX "PageLayout_PageId" on "PageLayout"("PageId");

CREATE UNIQUE INDEX "PageSetData_Identifier" on "PageSetData"("Identifier");

CREATE INDEX "Page_PageSetImageId" on "Page"("PageSetImageId");

CREATE UNIQUE INDEX "Page_UniqueId" on "Page"("UniqueId");

CREATE INDEX "ScanGroup_AudioCueRecordingId" on "ScanGroup"("AudioCueRecordingId");

CREATE INDEX "ScanGroup_PageLayoutId" on "ScanGroup"("PageLayoutId");

CREATE INDEX SymbolColorData_Identifier on SymbolColorData(Identifier);

CREATE INDEX VocabListEntry_VocabListId on VocabListEntry(VocabListId);

CREATE UNIQUE INDEX "VocabList_UniqueId" on "VocabList"("UniqueId");

CREATE INDEX "WhiteboardDoodlePath_WhiteboardId" on "WhiteboardDoodlePath"("WhiteboardId");

CREATE INDEX "WhiteboardImage_PageSetImageId" on "WhiteboardImage"("PageSetImageId");

CREATE UNIQUE INDEX "WhiteboardImage_UniqueId" on "WhiteboardImage"("UniqueId");

CREATE INDEX "WhiteboardImage_WhiteboardId" on "WhiteboardImage"("WhiteboardId");

CREATE UNIQUE INDEX "Whiteboard_UniqueId" on "Whiteboard"("UniqueId");

